spring:
  application:
    name: steaming-app

kafka:
  state-dir: /tmp/kafka-streams
  application-id: steaming-app
  bootstrap-servers: pkc-oxqxx9.us-east-1.aws.confluent.cloud:9092
  schema-registry-url: https://psrc-z6m5xyw.us-east-1.aws.confluent.cloud
  application-server: localhost:8080
  security-protocol: SASL_SSL
  sasl-mechanism: PLAIN
  sasl-jaas-config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"2WEAJASHMTCZC4YD\" password=\"cfltr8GYQ9YHna9RmQIVYjfR7Mn+Hi6xGB9T8pWbrumaLTiXSBURlGmdMxqsDBww\";"
  client-dns-lookup: use_all_dns_ips
  session-timeout-ms: 45000
  basic-auth-credentials-source: USER_INFO
  basic-auth-user-info: "ZQBGEF4ZI7KVMKWG:cfltuIg/1L2C0cMWXDrtpPcV0yvdsmQ0/1Z7qD5+OM13u7YkvT/56FuyS74D4BSQ"
  replication-factor: ${KAFKA_REPLICATION_FACTOR:3}
  min-insync-replicas: ${KAFKA_MIN_INSYNC_REPLICAS:2}
  commit-interval-ms: 0
  page-view-input-topic: test.streaming.page-view
  page-view-output-topic: test.streaming.page-view.output