spring:
  application:
    name: page-view-events-publisher

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:pkc-oxqxx9.us-east-1.aws.confluent.cloud:9092}
  schema-registry-url: ${SCHEMA_REGISTRY_URL:https://psrc-z6m5xyw.us-east-1.aws.confluent.cloud}
  topic-name: ${KAFKA_TOPIC:test.streaming.page-view}
  security-protocol: SASL_SSL
  sasl-mechanism: PLAIN
  sasl-jaas-config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"2WEAJASHMTCZC4YD\" password=\"cfltr8GYQ9YHna9RmQIVYjfR7Mn+Hi6xGB9T8pWbrumaLTiXSBURlGmdMxqsDBww\";"
  client-dns-lookup: use_all_dns_ips
  session-timeout-ms: ${KAFKA_SESSION_TIMEOUT_MS:45000}
  basic-auth-credentials-source: USER_INFO
  basic-auth-user-info: "ZQBGEF4ZI7KVMKWG:cfltuIg/1L2C0cMWXDrtpPcV0yvdsmQ0/1Z7qD5+OM13u7YkvT/56FuyS74D4BSQ"
  replication-factor: ${KAFKA_REPLICATION_FACTOR:3}
  min-insync-replicas: ${KAFKA_MIN_INSYNC_REPLICAS:2}
  commit-interval-ms: 0